### ISSUE TITLE
Not working in Firefox and Safari for MAC

### ISSUE THREAD

**Issue by mueezPL** [AllThingsSmitty/accessible-mega-menu#6]
Can you please share any solution about this issue. This keyboard controlled menu is not operating in Mozilla Firefox and Safari while using the tab button for this and I have tried many solutions. but nothing works for me. So please share any feedback or solution ASAP.

**Comment by AllThingsSmitty** [comment]
@mueezPL I'm not able to reproduce the problem you're describing. This works as described in Firefox and Safari. Tab to the first menu item and the use your arrow keys to expand that menu. The behavior is consistent in Chrome, too.
